config/routes.rb
SnackPrroject::Application.routes.draw do
  devise_for :users
	
	root :to => 'welcome#index'

  match 'admin' => 'admin#index'
  match 'new_category' => 'admin#new_category'
  match 'create_category' => 'admin#create_category'
  match 'create_article' => 'admin#create_article'
  match 'available_article' => 'admin#available_article'
  match 'commandes_liste' => 'admin#commandes_liste'
  match 'create_hour' => 'admin#create_hour'
  match 'liste_articles' => 'admin#liste_articles'
  match 'liste_categories' => 'admin#liste_categories'
  match 'articles_by_category/:id' => 'admin#articles_by_category'
  match 'edit_article/:id' => 'admin#edit_article'
  match 'update_article/:id' => 'admin#update_article'
  match 'valider_commande/:id' => 'admin#valider_commande'
  match 'commande_payee/:id' => 'admin#commande_payee'
  match 'total/:id' => 'admin#total'
  match 'delete_article/:id' => 'admin#delete_article'
  match 'edit_category/:id' => 'admin#edit_category'
  match 'delete_category/:id' => 'admin#delete_category'
  match 'update_category/:id' => 'admin#update_category'
  match 'parametre' => 'admin#hour_form'
  match 'sauce_liste' => 'admin#sauce_liste'
  match 'create_sauce' => 'admin#create_sauce'

  match 'articles_informations/:id' => 'welcome#articles_informations'
  match 'nom_commande' => 'welcome#nom_commande'
  match 'create_commande' => 'welcome#create_commande'
  match 'ajout_article/:id' => 'welcome#add_article'
  match 'plus_article/:id' => 'welcome#plus_article'
  match 'validate_commande/:id' => 'welcome#validate_commande'
  match 'mes_commandes' => 'welcome#archives_commande'
  match 'add_sauce/:id' => 'welcome#add_sauce'
  match 'remove_article/:id' => 'welcome#delete_article_from_commande'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :name, :price, :category_id, :attachment, :available, :sauce_id

  belongs_to :category
  belongs_to :commande
  belongs_to :sauce

  has_attached_file :attachment
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :articles
  has_many :sauces
end

app/models/commande.rb
class Commande < ActiveRecord::Base
  attr_accessible :name, :hour_id, :add_id

  belongs_to :hour
  belongs_to :user

  has_many :articles
end

app/models/fakesauce.rb
class Fakesauce < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/hour.rb
class Hour < ActiveRecord::Base
  belongs_to :user

  has_many :commandes
end

app/models/sauce.rb
class Sauce < ActiveRecord::Base
  attr_accessible :name, :category_id

  belongs_to :category

  has_many :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :start_hour, :end_hour, :intervalle, :name, :phone_number, :commande_max

  has_many :hours
  has_many :commandes
end

app/controllers/admin_controller.rb
#encoding: utf-8
class AdminController < ApplicationController

	before_filter :admin
	def index
		
	end

	def create_category
		@category = Category.new(params[:category])
		if @category.save
			redirect_to liste_categories_path
		end
	end

	def edit_article
		@article = Article.find(params[:id])
		@categories = Category.all
	end

	def update_article
		@article = Article.find(params[:id])
		if @article.update_attributes(params[:article])
			redirect_to :action => "articles_by_category", :id => @article.category_id
		end
	end

	def create_article
		@article = Article.new(params[:article])
		if @article.price == nil
			@article.price = 0
		end
		if @article.save
			redirect_to liste_articles_path
		end
		@categories = Category.all
	end

	def articles_by_category
		@category = Category.find(params[:id])
	end

	def commandes_liste
		@commandes = Commande.order(:hour_id).all
		@pretes = []
		@non_pretes = []
		@commandes.each do |c|
			if c.user_ready == true && c.ready == true && c.payee == false
				@pretes << c
			elsif c.user_ready == true && c.ready == false && c.payee == false
				@non_pretes << c
			end
		end
	end

	def liste_articles
		@articles = Article.all
		@base_article = []
		@articles.each do |a|
			if a.commande_id == nil
				@base_article << a
			end
		end
		@categories = Category.all
		@article = Article.new
	end

	def liste_categories
		@categories = Category.all
		@category = Category.new
	end

	def valider_commande
		@commande = Commande.find(params[:id])
		@commande.ready = true
		@commande.save
		redirect_to commandes_liste_path
	end

	def commande_payee
		@commande = Commande.find(params[:id])
		@commande.payee = true
		@commande.save
		@hour = @commande.hour
		@hour.destroy
		redirect_to commandes_liste_path
	end

	def delete_article
		@article = Article.find(params[:id])
		@article.delete
		@article.save
		redirect_to :action => "articles_by_category", :id => @article.category_id
	end

	def delete_category
		@category = Category.find(params[:id])
		@category.delete
		@category.save
		redirect_to :action => "liste_categories", :id => @category.id
	end

	def edit_category
		@category = Category.find(params[:id])
	end

	def update_category
		@category = Category.find(params[:id])
		if @category.update_attributes(params[:category])
			redirect_to :action => "liste_categories", :id => @category.id
		end
	end

	def hour_form
		@user = current_user
	end

	def create_hour
		@user = current_user
		@user.update_attributes(params[:user])
		@hours = Hour.find_all_by_user_id(@user.id)
		@hours.each do |h|
			h.destroy
		end
		@sh = @user.start_hour
		@eh = @user.end_hour + 15.minutes
		until @sh >= @eh
			h = Hour.new
			h.hour = @sh
			h.user = @user
			h.save
			@sh += @user.intervalle.minutes
		end
		redirect_to admin_path
	end

	def sauce_liste
		@categories = Category.all
		@sauces = Sauce.all
		@sauce = Sauce.new
	end

	def create_sauce
		@sauce = Sauce.new(params[:sauce])
		if @sauce.save
			if @sauce.name == ""
				@sauce.destroy
			end
			redirect_to sauce_liste_path
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def admin
  	if user_signed_in?
	  	if current_user.admin == false
	  		redirect_to root_path
	  	end
	  else
	  	redirect_to root_path
	  end
  end
end

app/controllers/welcome_controller.rb
#encoding: utf-8
class WelcomeController < ApplicationController

	def index
		@categories = Category.all
	end

	def articles_informations
		@article = Article.find(params[:id])
	end

	def nom_commande
		if Hour.count < 1
			redirect_to root_path
			flash[:notice] = "Aucune heure disponible"
		end
		if user_signed_in?
			@user = current_user
		end
		@hours = []
		Hour.all.each do |h|
			if h.commandes.count < User.find_by_admin(true).commande_max
				if h.hour.hour > Time.now.hour
					@hours << h
				else
					if h.hour.min > Time.now.min
						@hours << h
					end
				end
			end
		end
		@commande = Commande.new
	end

	def create_commande
		@commande = Commande.new(params[:commande])
		if @commande.save
			if user_signed_in?
				@commande.user = current_user
			end
			@commande.save
			redirect_to :action => "add_article", :id => @commande.id
		end
	end

	def add_article
		@commande = Commande.find(params[:id])
		@articles = Article.all
		@good_articles = []
		@articles.each do |a|
			if a.commande_id == nil
				@good_articles << a
			end
		end
		@sauces = Sauce.all
	end

	def plus_article
		@commande = Commande.find(params[:id])
		@commande.update_attributes(params[:commande])
		@article = Article.find(@commande.add_id)
		@new_article = Article.new
		@new_article.name = @article.name
		@new_article.price = @article.price
		@new_article.category = @article.category
		@new_article.attachment = @article.attachment
		@new_article.description = @article.description
		@new_article.commande = @commande
		@new_article.save
		redirect_to :action => "add_article", :id => @commande.id
	end

	def validate_commande
		@commande = Commande.find(params[:id])
		@commande.user_ready = true
		@commande.save
		redirect_to root_path, :notice => "Commande validée"
	end

	def archives_commande
		@commandes = current_user.commandes
	end

	def add_sauce
		@article = Article.find(params[:id])
		@article.update_attributes(params[:article])
		redirect_to :action => "add_article", :id => @article.commande_id
	end

	def delete_article_from_commande
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to :action => "add_article", :id => @article.commande_id
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/articles_by_category.html.haml
.row.offset1
	%h3
		= "Articles de la catégorie"
		= @category.name
	%br/
.row
	.span6.offset1
		- if @category.articles.count == 0
			%p
				= "Auncun article à afficher"	
		- else
			- @category.articles.each do |a|
				%p{:class => "span3"}
					= a.name
					%br/
					= a.price
					= "€"
					= image_tag a.attachment, size: "75x75"
					= button_to "Editer l'article", :action => "edit_article", :id => a.id
					= button_to "Supprimer l'article", :action => "delete_article", :id => a.id					
				%br/
				= "Disponible : "
				- if a.available == true
					= "Oui"
				- else
					= "Non"
				%br/
				%br/
		= button_to "Retour", :action => "liste_articles"

app/views/admin/commandes_liste.html.haml
%meta{content: "92", "http-equiv" => "refresh"}/
.row
	.span5.offset1
		%h3
			= "Nouvelles Commandes"
	.span6
		%h3
			= "Commandes Prêtes"
%br/
.row
	.span3.offset1	
		- if @non_pretes.count == 0
			= "Il n'y a aucune commande"
		- else
			- @non_pretes.each do |c|
				%p{:style => "border: 1px solid black"}
					= c.name
					= ""
					= c.hour.hour.to_formatted_s(:time)
					%br/
					%br/
					- c.articles.each do |ca|
						= ca.name
						.offset1
							- if ca.sauce == nil
								= "Aucune sauce pour ce sandwich"
							- else
								= ca.sauce.name
						%br/	
					= button_to "Prête", :action => "valider_commande", :id => c.id
	.span3.offset2	
		- if @pretes.count == 0
			= "Il n'y a aucune commande prête"
		- else
			- @pretes.each do |c|
				%p{:style => "border: 1px solid black"}
					= c.name
					= ""
					= c.hour.hour.to_formatted_s(:time)
					%br/
					%br/
					- c.articles.each do |ca|
						= ca.name
						%br/
						- if ca.sauce == nil
							= "Aucune sauce pour ce sandwich"
						- else
							= "&nbsp;&nbsp;&nbsp;&nbsp;#{ca.sauce.name}".html_safe
						%br/
						%br/
					%br/
					= "Total à payer : "
					= c.articles.sum('price')
					= "€"
					= button_to "Payée", :action => "commande_payee", :id => c.id
.offset1
	= button_to "Retour", admin_path

app/views/admin/edit_article.html.haml
.offset1
	= form_for @article, :url => url_for(:action => "update_article", :id => @article.id) do |f|
		= "Nom article"
		%br/
		= f.text_field :name
		%br/
		%br/
		= "Catégorie"
		%br/
		= select :article, "category_id", @categories.map {|u| [u.name, u.id]}
		%br/
		%br/
		= "Prix"
		%br/
		= f.text_field :price
		= "€"
		%br/
		%br/
		= f.file_field :attachment
		%br/
		%br/
		= select :article, "available", [['Disponible', true], ['Indisponible', false]]
		%br/
		= f.submit 'Valider'

app/views/admin/edit_category.html.haml
.offset1
	= form_for @category, :url => url_for(:action => "update_category", :id => @category.id) do |f|
		= "Nom catégorie"
		%br/
		= f.text_field :name
		%br/
		%br/
		= f.submit 'Valider'

app/views/admin/hour_form.html.haml
= form_for @user, :url => url_for(:action => "create_hour") do |f|
	.span6
		= f.label "Heure de début"
		= f.time_select :start_hour
	.span3
		= f.label "Intervalle entre chaque commande en minutes"
		= f.number_field :intervalle
	%br/
	.span6
		= f.label "Heure de fin"
		= f.time_select :end_hour
	.span3
		= f.label "Nombre de commande max acceptées par intervalle"
		= f.number_field :commande_max
	%br/
	.span3
		= f.submit "Valider", :class => "btn btn-primary"

app/views/admin/index.html.haml
%h4.span4.offset1
	= link_to 'Commandes', commandes_liste_path
%h4.span4  
	= link_to 'Catégories', liste_categories_path
%h4.span3
	= link_to 'Articles', liste_articles_path
%h4.span3.offset1
	= link_to 'Sauces', sauce_liste_path
%h4.span4
	= link_to 'Paramètres Restaurateur', parametre_path

app/views/admin/liste_articles.html.haml
.span6
	.offset1
		%h2
			= "Articles"
		%p
			%br/
			- if @base_article.count == 0
				= "Auncun article à afficher"	
			- else
				- @categories.each do |c|
					- if c.articles.count > 0
						= link_to c.name, :action => "articles_by_category", :id => c.id
						%br/
						- c.articles.each do |ca|
							- if ca.commande_id == nil
								= "- "
								= ca.name
								%br/
						%br/
		%br/
		= button_to "Retour", admin_path
.span5
	%h3
		= "+ Ajouter un article"
	= form_for @article, :url => create_article_path do |f|
		= "Nom article"
		%br/
		= f.text_field :name
		%br/
		%br/
		= "Catégorie"
		%br/
		= select :article, "category_id", @categories.map {|u| [u.name, u.id]}, include_blank: true
		%br/
		%br/
		= "Prix"
		%br/
		= f.text_field :price
		= "€"
		%br/
		%br/
		= f.file_field :attachment
		%br/
		%br/
		= f.submit 'Valider'

app/views/admin/liste_categories.html.haml
.row.offset1
	%h2.span6
		= "Catégories"
	%h3.span5
		= "+ Ajouter une catégorie"
%br/
.row
	.span6
		.offset1	
			- if @categories.count == 0
				= "Auncune catégorie à afficher"	
			- else
				- @categories.each do |c|
					%p{:style => "margin-bottom: 0px"}
						= c.name
						%br/
						%div{:style => "font-size: 12px"}
							= link_to "Editer la catégorie", :action => "edit_category", :id => c.id
							%br/
							= link_to "Supprimer la catégorie", {:action => "delete_category", :id => c.id}, :confirm=>"Si vous supprimez la catégorie, les articles associés seront supprimés avec. Voulez-vous continuez ?"
			%br/		
			= button_to "Retour", admin_path
	.span5
		= form_for @category, :url => create_category_path do |f|
			%p
				= "Nom catégorie"
				%br/
				= f.text_field :name
				%br/
				%br/
				= f.submit 'Valider'

app/views/admin/sauce_liste.html.haml
.span6
	%h3
		= "Sauces disponible"
	- @categories.each do |c| 
		%h4
			= c.name
		.offset3
			- @sauces.each do |s|
				- if s.category == c
					= s.name
					%br/
.span6
	%h3
		= "Ajouter une nouvelle sauce"
	= form_for @sauce, :url => create_sauce_path do |f|
		.row
			= f.label "Nom de la sauce"
			= f.text_field :name
		.row
			= f.label "Categorie de la sauce"
			= select :sauce, "category_id", @categories.map {|u| [u.name, u.id]}
		.row
			%br/
			= f.submit "Valider", :class => "btn btn-primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Snack Project
    = stylesheet_link_tag "application", "jquery-ui", "bootstrap", "addon"
    = javascript_include_tag "application", "bootstrap-dropdown"
    %meta{ :name => "viewport", :content =>"width=device-width, initial-scale=1.0"}
    = csrf_meta_tags
  %body  
    .container
      .navbar
        .navbar-inner
          - if current_user && current_user.admin == true
            = link_to "Admin", admin_path, :class => "brand"
          - else  
            = link_to "Snack Project", root_path, :class => "brand"
          = link_to "Commander", nom_commande_path, :class => "brand"
          %ul.nav.pull-right
            - if user_signed_in?
              %li.dropdown
                %a(href="#" class="dropdown-toggle" data-toggle="dropdown")
                  = current_user.email
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to 'Mes paramètres', edit_user_registration_path
                  %li
                    = link_to 'Se déconnecter', destroy_user_session_path, :method => :delete
            - else
              %li
                = link_to 'Créer un compte', new_user_registration_path
              %li
                = link_to 'Se connecter', new_user_session_path
      - if notice
        %p.notice
          .alert.success.fade.in
            %a.close(data-dismiss="alert") &times;
            = notice
      - if alert
        .alert.warning.fade.in
          %a.close(data-dismiss="alert") &times;
          %p= alert
      .row-fluid
        .span12
          = yield


          

             
      %br/
  %footer.footer
    .container{:style => "padding: 15px 0;"}
      .row
        .span5.offset1
          = "Application réalisée par l'entreprise "
          = link_to "Eric-Orlandini.fr", "http://www.eric-orlandini.fr", :target => "_blank"
        .span3.offset2
          = " Retrouvez nous sur "
          = link_to "Facebook", "http://www.facebook.com/EricOrlandinifr", :target => "_blank"

app/views/welcome/add_article.html.haml
.span6
	- @commande.total_price = 0
	- @commande.articles.each do |a|
		.row
			.span6
				%h4
					= a.name
					%br/
					= a.price
					= "€"
					%br/
					= link_to "Supprimer l'article", :action => "delete_article_from_commande", :id => a.id, :class => "btn btn-primary"
				- @commande.total_price += a.price
				%br/
			.span6
				- if a.attachment.exists?
					= image_tag a.attachment, :size => "300x300"
				- else
					%h4
						= "Aucune image pour ce produit"
				- @article = a
				- if a.sauce == nil
					- @final_sauces = []
					- @sauces.each do |s|
						- if s.category == a.category
							- @final_sauces << s
					= form_for @article, :url => url_for(:action => "add_sauce", :id => @article.id) do |f|
						.row
							= f.label "Choisissez une sauce"
							= select :article, "sauce_id", @final_sauces.map {|u| [u.name, u.id]}, :prompt => "Aucune sauce"
						.row
							%br/
							= f.submit "Valider", :class => "btn btn-primary"
				- else
					.offset1
						%h5
							= "Sauce choisie: "
							= a.sauce.name
	%br/
	%h4
		= "Prix total de la commande:"
		= @commande.total_price
		= "€"
.span6
	%h3
		= "Rajoutez un produit à votre commande"
	= form_for @commande, :url => url_for(:action => "plus_article", :id => @commande.id) do |f|
		.row{:style => "text-align:center"}
			= f.label "Produit"
			= select :commande, "add_id", @good_articles.map {|u| [u.name, u.id]}
			%br/
			%br/
			= f.submit "Ajouter produit", :class => "btn btn-primary"
	%br/
	%br/
	%h3
		= "Validez votre commande"
	.row{:style => "text-align:center"}
		= link_to "OK", {:action => "validate_commande", :id => @commande.id}, :class => "btn btn-primary"

app/views/welcome/archives_commande.html.haml
%h3
	= "Mes commandes"
%br/
- @commandes.each do |c|
	.span4
		.span3
			= c.hour.hour.to_formatted_s(:time)
		.span1
			- c.articles.each do |a|
				= a.name
				%br/

app/views/welcome/articles_informations.html.haml
.span6
	%h4
		= @article.name
	%br/
	%div{:style => "margin-left:10%"}
		.span4
			= @article.description
		.span4
			= @article.price
.span6
	%br/
	- if @article.attachment.exists?
		= image_tag @article.attachment

app/views/welcome/index.html.haml
- @categories.each do |c|
	- if c.articles.count > 0 
		.span4
			%h4
				= c.name
			%div{:style => "text-align:center"}
				- c.articles.each do |a|
					- if a.commande_id == nil
						= link_to a.name, :action => "articles_informations", :id => a.id
						%br/

app/views/welcome/nom_commande.html.haml
%h3{:style => "text-align:center"}
	= "Nouvelle commande"
= form_for @commande, :url => create_commande_path do |f|
	.span3
		= f.label "Nom de la commande"
		- if @user
			= f.text_field :name, :value => @user.name
		- else
			= f.text_field :name
	.span3
		= f.label "Heure de retrait de commande"
		= select :commande, "hour_id", @hours.map {|u| [u.hour.to_formatted_s(:time), u.id]}
	.span3
		%br/
		= f.submit "Valider", :class => "btn btn-primary"